[package]
authors = ["MÃ¨ir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"
name = "rfw-math"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = ">=0.17"
serde = { version = "1.0", optional = true }