[package]
name = "bvh"
version = "0.1.0"
authors = ["MÃ¨ir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7.3"
glam = "0.8.6"
num_cpus = "1.12.0"
rayon = "1.3.0"
serde = { version = "1.0", features = ["derive"] }