[package]
name = "scene"
version = "0.1.0"
authors = ["MÃ¨ir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tobj = "0.1.12"
bvh = { path = "../bvh" }
rayon = "1.3.0"
num_cpus = "1.12.0"
glam = "0.8.6"
wgpu = "0.4.0"